version: '3.8'
services:
  app:
    build: ./app
    container_name: s7ben-med-019
    ports: ["5047:8096"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8096/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
