
services:
  web-app:
    build: ./web-app
    container_name: lfi-webapp
    hostname: web-app
    ports:
      - "5078:80"
    volumes:
      - lfi-logs:/var/log/apache2
    networks:
      lfi-net:
        ipv4_address: 10.200.10.10
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health.php"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 120s

  file-server:
    build: ./file-server
    container_name: lfi-fileserver
    hostname: file-server
    expose:
      - "80"
    networks:
      lfi-net:
        ipv4_address: 10.200.10.20
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  log-server:
    build: ./log-server
    container_name: lfi-logserver
    hostname: log-server
    volumes:
      - lfi-logs:/var/log/apache2
    networks:
      lfi-net:
        ipv4_address: 10.200.10.30
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health.php"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  lfi-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.200.10.0/24

volumes:
  lfi-logs:
