services:
  app:
    build:
      context: ./app
      args:
        - FLAG
    ports:
      - "5000:5000"
    environment:
      - FLAG=${FLAG:-S7BEN{CSRF_ATT4CK_SUCC3SSFUL}}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
