server.port=8080
spring.application.name=vulnerable-webapp

# Logging
logging.level.root=INFO
logging.level.com.strike7=DEBUG

# Disable security for easier exploitation
management.security.enabled=false
