# Server Configuration
server.port=8080

# Logging
logging.level.root=INFO
logging.level.com.strike7.xxe=DEBUG

# Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
