version: '3.8'
services:
  app:
    build: ./app
    container_name: s7ben-med-013
    ports: ["5022:8095"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8095/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
